[
    {
        "content": "<p>How to run tests like <code>compiler/rustc_error_codes/src/error_codes/E0164.md</code> and annotated code block with <code>compile_fail,E0164</code>?<br>\nIt seems doc tests and I run <code>./x.py test --doc</code> with must fail annotation, but the command success.</p>",
        "id": 218671677,
        "sender_full_name": "sasurau4",
        "timestamp": 1606988868
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"331219\">@sasurau4</span> <code>./x.py test src/tools/error_index_generator</code>   That extracts all the docs into a single markdown file, then runs <code>rustdoc --test</code> on it it.</p>",
        "id": 218715029,
        "sender_full_name": "Eric Huss",
        "timestamp": 1607011591
    },
    {
        "content": "<p>Thanks. Addition, <code>rustdoc --test ./build/x86_64-unknown-linux-gnu/test/error-index.md</code> caused  62 fail tests in my local. Because they use feature attribute and emit message like <code>'#![feature]' may not be used on the stable release channel</code>. How to run  doc test same as CI locally?</p>",
        "id": 218841382,
        "sender_full_name": "sasurau4",
        "timestamp": 1607093293
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"331219\">@sasurau4</span> you need the same version of rustdoc</p>",
        "id": 218841494,
        "sender_full_name": "Joshua Nelson",
        "timestamp": 1607093345
    },
    {
        "content": "<p>either beta with RUSTC_BOOTSTRAP or the latest nightly</p>",
        "id": 218841515,
        "sender_full_name": "Joshua Nelson",
        "timestamp": 1607093354
    },
    {
        "content": "<p>but you can never get the <em>exact</em> version of nightly because the master branch has changes from the last 24 hours, so it's better to use x.py where possible</p>",
        "id": 218841621,
        "sender_full_name": "Joshua Nelson",
        "timestamp": 1607093398
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"232545\">@Joshua Nelson</span> Thanks <span aria-label=\"thumbs up\" class=\"emoji emoji-1f44d\" role=\"img\" title=\"thumbs up\">:thumbs_up:</span>  When I use dev from rustup, rustdoc works fine. I see. <br>\nCan I run <code>error-index.md</code> from x.py? The command <code>./x.py test --doc build/x86_64-unknown-linux-gnu/test/error-index.md</code> doesn't succeed.</p>",
        "id": 218842595,
        "sender_full_name": "sasurau4",
        "timestamp": 1607093811
    },
    {
        "content": "<p>I would not expect anything with build/ at the front to work</p>",
        "id": 218842817,
        "sender_full_name": "Joshua Nelson",
        "timestamp": 1607093901
    },
    {
        "content": "<p>maybe <code>x.py test compiler/error_index</code> or something like that</p>",
        "id": 218842844,
        "sender_full_name": "Joshua Nelson",
        "timestamp": 1607093913
    },
    {
        "content": "<p>I see. <code>./x.py test compiler/rustc_error_codes</code> run 0 tests and <code>x.py test compiler/error_index</code> fail with no rules matched. <br>\nMy question is how to check error code in my local and I have understood how to do it. Thanks for your replies!</p>",
        "id": 218844944,
        "sender_full_name": "sasurau4",
        "timestamp": 1607094860
    }
]