[
    {
        "content": "<p>I'm seeing an error that doesn't make any sense to me. I'm curious if I should file this as a bug in the compiler or if there's a legitimate problem with my code. Link to playground: <a href=\"https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=315c87d507b242669f2b6243dc802b53\" target=\"_blank\" title=\"https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=315c87d507b242669f2b6243dc802b53\">https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=315c87d507b242669f2b6243dc802b53</a> (edit: simplified code in playground)</p>",
        "id": 184616066,
        "sender_full_name": "Paul Faria",
        "timestamp": 1577917462
    },
    {
        "content": "<p>I could understand if the problem was on line 31, where I'm getting a reference that locks self to immutable, and then I can't pass self as a mutable reference. But the error pointing to line 27 makes no sense, especially since line 28 immediately returns that value!</p>",
        "id": 184616089,
        "sender_full_name": "Paul Faria",
        "timestamp": 1577917537
    },
    {
        "content": "<p>My thought to fix the (or what  I thought was the original) error was to add a call to <code>clone</code> (see modified example here: <a href=\"https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=beaa001ec10a1d7b5eeec6bc77103180\" target=\"_blank\" title=\"https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=beaa001ec10a1d7b5eeec6bc77103180\">https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2018&amp;gist=beaa001ec10a1d7b5eeec6bc77103180</a>) on line 31, but I still run into the same issue.</p>",
        "id": 184616143,
        "sender_full_name": "Paul Faria",
        "timestamp": 1577917604
    },
    {
        "content": "<p>Here's another variation further simplified without any async: <a href=\"https://play.rust-lang.org/?version=nightly&amp;mode=debug&amp;edition=2018&amp;gist=425f9be6798d37b7291582629ac184cb\" target=\"_blank\" title=\"https://play.rust-lang.org/?version=nightly&amp;mode=debug&amp;edition=2018&amp;gist=425f9be6798d37b7291582629ac184cb\">https://play.rust-lang.org/?version=nightly&amp;mode=debug&amp;edition=2018&amp;gist=425f9be6798d37b7291582629ac184cb</a></p>",
        "id": 184618615,
        "sender_full_name": "Paul Faria",
        "timestamp": 1577922327
    },
    {
        "content": "<p>I was able to solve it with this version: <a href=\"https://play.rust-lang.org/?version=nightly&amp;mode=debug&amp;edition=2018&amp;gist=ecdc7880c62b9071abd4971a07c0b012\" target=\"_blank\" title=\"https://play.rust-lang.org/?version=nightly&amp;mode=debug&amp;edition=2018&amp;gist=ecdc7880c62b9071abd4971a07c0b012\">https://play.rust-lang.org/?version=nightly&amp;mode=debug&amp;edition=2018&amp;gist=ecdc7880c62b9071abd4971a07c0b012</a> I find it pretty unexpected to be honest though. Is this an edge case fixed by polonius?</p>",
        "id": 184618733,
        "sender_full_name": "Paul Faria",
        "timestamp": 1577922530
    },
    {
        "content": "<p>Yes. Pretty sure this is another form of <a href=\"https://stackoverflow.com/q/38023871/155423\" target=\"_blank\" title=\"https://stackoverflow.com/q/38023871/155423\">Returning a reference from a HashMap or Vec causes a borrow to last beyond the scope it's in?</a>.</p>",
        "id": 184622905,
        "sender_full_name": "Jake Goulding",
        "timestamp": 1577930951
    },
    {
        "content": "<p>And yes, Polonius should address it; this is NLL case <a href=\"https://github.com/rust-lang/rust/issues/3\" target=\"_blank\" title=\"https://github.com/rust-lang/rust/issues/3\">#3</a>.</p>",
        "id": 184622914,
        "sender_full_name": "Jake Goulding",
        "timestamp": 1577930995
    },
    {
        "content": "<p>Ok, that's helpful to know. Thank you!</p>",
        "id": 184626578,
        "sender_full_name": "Paul Faria",
        "timestamp": 1577937903
    }
]