[
    {
        "content": "<p>I filed <a href=\"https://github.com/rust-lang/rust/issues/80179\">rust-lang/rust#80179</a>, and it was closed with a fix. However, I've found another case where the issue happens. I can't find a way to reopen the issue. Should I file a new one?</p>",
        "id": 222178973,
        "sender_full_name": "Ruby Lazuli",
        "timestamp": 1610212203
    },
    {
        "content": "<p>Filing a new issue is fine, yes. Feel free to cc the old one.</p>",
        "id": 222179000,
        "sender_full_name": "simulacrum",
        "timestamp": 1610212266
    }
]