<html>
<head><meta charset="utf-8"><title>Error Chain stabilization · project-error-handling · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://zulip-archive.rust-lang.org/stream/257204-project-error-handling/index.html">project-error-handling</a></h2>
<h3>Topic: <a href="https://zulip-archive.rust-lang.org/stream/257204-project-error-handling/topic/Error.20Chain.20stabilization.html">Error Chain stabilization</a></h3>

<hr>

<base href="https://rust-lang.zulipchat.com">

<head><link href="https://zulip-archive.rust-lang.org/style.css" rel="stylesheet"></head>

<a name="259726136"></a>
<h4><a href="https://rust-lang.zulipchat.com#narrow/stream/257204-project-error-handling/topic/Error%20Chain%20stabilization/near/259726136" class="zl"><img src="https://zulip-archive.rust-lang.org/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Jakub Duchniewicz <a href="https://zulip-archive.rust-lang.org/stream/257204-project-error-handling/topic/Error.20Chain.20stabilization.html#259726136">(Oct 30 2021 at 11:38)</a>:</h4>
<p>I started to work on issue <a href="https://github.com/rust-lang/rust/issues/58520">#58520</a> where <span class="user-mention" data-user-id="311727">@Harald Hoyer</span> proposed and implemented the <code>chain()</code> method on <code>Error</code>. I looked through the outstanding issues and past ones and it looks to me like the most important one to be solved is <a href="https://github.com/rust-lang/rust/issues/69161">this one</a> where an ambiguity is introduced due to two matching implementation of the <code>chain()</code> function. The second one is probably just a change in underlying iterator type to use <code>FusedIterator</code> instead of a regular one.</p>



<a name="259726213"></a>
<h4><a href="https://rust-lang.zulipchat.com#narrow/stream/257204-project-error-handling/topic/Error%20Chain%20stabilization/near/259726213" class="zl"><img src="https://zulip-archive.rust-lang.org/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Jakub Duchniewicz <a href="https://zulip-archive.rust-lang.org/stream/257204-project-error-handling/topic/Error.20Chain.20stabilization.html#259726213">(Oct 30 2021 at 11:41)</a>:</h4>
<p>I wonder if <a href="https://github.com/rust-lang/rust/pull/90104">https://github.com/rust-lang/rust/pull/90104</a> does not solve this issue where we could disable one implementation of this function</p>



<a name="259726265"></a>
<h4><a href="https://rust-lang.zulipchat.com#narrow/stream/257204-project-error-handling/topic/Error%20Chain%20stabilization/near/259726265" class="zl"><img src="https://zulip-archive.rust-lang.org/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Jakub Duchniewicz <a href="https://zulip-archive.rust-lang.org/stream/257204-project-error-handling/topic/Error.20Chain.20stabilization.html#259726265">(Oct 30 2021 at 11:42)</a>:</h4>
<p>The second one seems perfectly sound to be implemented instantly as <code>FusedIterator</code> always returns <code>None</code> when it has been exhausted and that is what we want in case of iterating through a finite chain of errors</p>



<a name="259726361"></a>
<h4><a href="https://rust-lang.zulipchat.com#narrow/stream/257204-project-error-handling/topic/Error%20Chain%20stabilization/near/259726361" class="zl"><img src="https://zulip-archive.rust-lang.org/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Jakub Duchniewicz <a href="https://zulip-archive.rust-lang.org/stream/257204-project-error-handling/topic/Error.20Chain.20stabilization.html#259726361">(Oct 30 2021 at 11:45)</a>:</h4>
<p>apart from these two issues it does not look like there is a lot to tweak in this implementation. We could also wait for Generic Member Access and come up with a totally different way of extracting a chain of errors, for example, with a <code>.context::&lt;Chain&gt;()</code> call</p>



<hr><p>Last updated: Apr 12 2022 at 20:01 UTC</p>
</html>