[
    {
        "content": "<p>A few prs are failing in the queue due to binutils:</p>\n<ul>\n<li><a href=\"https://github.com/rust-lang-ci/rust/runs/5570997126?check_suite_focus=true\">https://github.com/rust-lang-ci/rust/runs/5570997126?check_suite_focus=true</a></li>\n<li><a href=\"https://github.com/rust-lang-ci/rust/runs/5572429490?check_suite_focus=true\">https://github.com/rust-lang-ci/rust/runs/5572429490?check_suite_focus=true</a></li>\n</ul>",
        "id": 275533887,
        "sender_full_name": "DPC",
        "timestamp": 1647446736
    },
    {
        "content": "<p>cc <span class=\"user-mention\" data-user-id=\"116122\">@simulacrum</span></p>",
        "id": 275537100,
        "sender_full_name": "DPC",
        "timestamp": 1647447784
    },
    {
        "content": "<p>Please close the tree if it's causing everything to fail; I won't have a chance to look for some time.</p>",
        "id": 275537232,
        "sender_full_name": "simulacrum",
        "timestamp": 1647447833
    },
    {
        "content": "<p>seems like bors is unresponsive as well <span aria-label=\"cry\" class=\"emoji emoji-1f622\" role=\"img\" title=\"cry\">:cry:</span></p>",
        "id": 275539484,
        "sender_full_name": "DPC",
        "timestamp": 1647448580
    },
    {
        "content": "<p>Github is having issues: <a href=\"https://www.githubstatus.com/incidents/fpk08rxnqjz2\">https://www.githubstatus.com/incidents/fpk08rxnqjz2</a></p>",
        "id": 275539692,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647448662
    },
    {
        "content": "<p>dpc was using <a href=\"https://github.com/rust-lang/rust/pull/95000\">https://github.com/rust-lang/rust/pull/95000</a> to test the binutils issue, it failed a couple hours ago, should it be retried or does the failure mean there needs to be manual investigation ?</p>",
        "id": 275576857,
        "sender_full_name": "lqd",
        "timestamp": 1647464577
    },
    {
        "content": "<p>The actual failure is during the cmake build:</p>\n<blockquote>\n<p>/scripts/cmake.sh: line 14: /tmp/build.log: Permission denied</p>\n</blockquote>\n<p>It fails because it can't redirect into the log file? And then prints the old log from the binutils build.</p>",
        "id": 275579325,
        "sender_full_name": "Nikita Popov",
        "timestamp": 1647465854
    },
    {
        "content": "<p>And of course, it's another of those docker images that only continue working thanks to the cache, so can't be run locally...</p>",
        "id": 275579583,
        "sender_full_name": "Nikita Popov",
        "timestamp": 1647466019
    },
    {
        "content": "<p>I'm preparing my bump-linux-gnu PR right now -- but it will need FCP, so that won't be a quick fix.</p>",
        "id": 275583094,
        "sender_full_name": "cuviper",
        "timestamp": 1647468004
    },
    {
        "content": "<p>if we need to do a quick baby-step bump for ppc like we did for s390x, that should be fine</p>",
        "id": 275583214,
        "sender_full_name": "cuviper",
        "timestamp": 1647468046
    },
    {
        "content": "<p>Does anyone know why the docker cache seems to have been deleted?</p>",
        "id": 275585874,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647469984
    },
    {
        "content": "<p>It times out after some time by itself, currently</p>",
        "id": 275586077,
        "sender_full_name": "simulacrum",
        "timestamp": 1647470131
    },
    {
        "content": "<p>retrying the top of queue pr now</p>",
        "id": 275586913,
        "sender_full_name": "DPC",
        "timestamp": 1647470829
    },
    {
        "content": "<p>Just tried running dist-powerpc64-linux while copying ca bundle from ubuntu 20.04, but that  still fails the cross tool chain build (in \"Installing C library\" phase) before getting to cmake.</p>",
        "id": 275586957,
        "sender_full_name": "Nikita Popov",
        "timestamp": 1647470870
    },
    {
        "content": "<p>Looks like the current CI run is past the problematic part already, so issue resolved itself :)</p>",
        "id": 275588006,
        "sender_full_name": "Nikita Popov",
        "timestamp": 1647471623
    },
    {
        "content": "<p>hiya, what's the status on CI being un-broken and rustc tree being opened back up?</p>",
        "id": 275601410,
        "sender_full_name": "Michael Goulet (compiler-errors)",
        "timestamp": 1647484613
    },
    {
        "content": "<p>I reopened it</p>",
        "id": 275601523,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647484793
    },
    {
        "content": "<p>I think the original issue was related to the github outage.</p>",
        "id": 275601531,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647484802
    },
    {
        "content": "<p>The last PR failed with a strange error, though, that is not obvious to me why it failed</p>",
        "id": 275601576,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647484820
    },
    {
        "content": "<p>Ah: <code>error: failed to write /tmp/rustceAvTxY/lib.rmeta: No space left on device (os error 28)</code></p>",
        "id": 275601715,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647485013
    },
    {
        "content": "<p>For some reason, the root partition is way smaller than the most recent build:</p>\n<p><code>/dev/root       667G   52G  616G   8% /</code></p>\n<p>vs</p>\n<p><code>/dev/root        84G   52G   33G  62% /</code></p>",
        "id": 275602155,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647485583
    },
    {
        "content": "<p>hm, perhaps that's why bors failed on <a href=\"https://github.com/rust-lang/rust/issues/95020\">#95020</a>..</p>",
        "id": 275602267,
        "sender_full_name": "Michael Goulet (compiler-errors)",
        "timestamp": 1647485753
    },
    {
        "content": "<p>oh wait that's ppc failing, i bet the underlying issue didn't get fixed?</p>",
        "id": 275602314,
        "sender_full_name": "Michael Goulet (compiler-errors)",
        "timestamp": 1647485779
    },
    {
        "content": "<p>Hm.  The docker cache failed to download again.  Very strange.</p>",
        "id": 275602333,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647485830
    },
    {
        "content": "<p>well, perhaps tree should be closed again since it didn't get fixed :/</p>",
        "id": 275602337,
        "sender_full_name": "Michael Goulet (compiler-errors)",
        "timestamp": 1647485844
    },
    {
        "content": "<p>yep, closed it again.</p>",
        "id": 275602348,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647485875
    },
    {
        "content": "<p>I didn't intend to restart the top PR, but we'll see how it goes.</p>",
        "id": 275602732,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647486305
    },
    {
        "content": "<p>I gotta go for a bit, but I'll be back later.</p>",
        "id": 275602742,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647486313
    },
    {
        "content": "<p>I really wish it was possible to see CI logs while the job is running.</p>",
        "id": 275602782,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647486362
    },
    {
        "content": "<p>I don't really understand what is going on. Summary:</p>\n<p>Starting with <a href=\"https://github.com/rust-lang-ci/rust/actions/runs/1992757249\">https://github.com/rust-lang-ci/rust/actions/runs/1992757249</a>, dist-powerpc64-linux failed. For some reason, it failed to download the docker cache (with a 404). While rebuilding the docker image, it fails while rebuilding cmake with the error:</p>\n<div class=\"codehilite\"><pre><span></span><code>/scripts/cmake.sh: line 14: /tmp/build.log: Permission denied\nERROR: An error was encountered with the build.\n</code></pre></div>\n<p>It is not clear why that is happening. I tried building that docker image with <code>--no-cache</code> locally, and it built fine.</p>\n<p>Strangely, later in the day, <a href=\"https://github.com/rust-lang-ci/rust/actions/runs/1995522014\">https://github.com/rust-lang-ci/rust/actions/runs/1995522014</a> the dist-powerpc64-linux builder ran just fine. It was able to download the docker cache and finished. However, the dist-arm-linux image ran out of disk space because the root partition was way smaller than normal.</p>\n<p>Then, the very next PR, at <a href=\"https://github.com/rust-lang-ci/rust/actions/runs/1996293142\">https://github.com/rust-lang-ci/rust/actions/runs/1996293142</a> went back to failing on dist-powerpc64-linux.</p>\n<p>The logs aren't really showing anything obvious what is causing this.</p>",
        "id": 275605628,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647490278
    },
    {
        "content": "<p>going to run <a href=\"https://github.com/rust-lang/rust/issues/95000\">#95000</a> just to see if the problem still resurfaces or not</p>",
        "id": 275611530,
        "sender_full_name": "DPC",
        "timestamp": 1647498051
    },
    {
        "content": "<p>the answer is it still errors <span aria-label=\"sob\" class=\"emoji emoji-1f62d\" role=\"img\" title=\"sob\">:sob:</span></p>",
        "id": 275612449,
        "sender_full_name": "DPC",
        "timestamp": 1647499285
    },
    {
        "content": "<p>Any way I can help with this issue?</p>",
        "id": 275677044,
        "sender_full_name": "David Koloski",
        "timestamp": 1647532890
    },
    {
        "content": "<p>I pushed <a href=\"https://github.com/rust-lang/rust/issues/95050\">#95050</a> which I think should fix the problem.  I saw that <span class=\"user-mention\" data-user-id=\"133224\">@Nikita Popov</span> had opened a similar PR, but I'm not sure if they are around to get their PR ready to merge.</p>",
        "id": 275708319,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647542863
    },
    {
        "content": "<p>Looks like the tree <a href=\"https://github.com/rust-lang/rust/pull/95020#issuecomment-1071193115\">was reopened</a> without a fix having landed. Do we want to close the tree again and give <a href=\"https://github.com/rust-lang/rust/issues/95050\">#95050</a> p=100 so other PRs queued up to merge don't keep failing?</p>",
        "id": 275708729,
        "sender_full_name": "Michael Goulet (compiler-errors)",
        "timestamp": 1647543037
    },
    {
        "content": "<p>Oh, yea, <span class=\"user-mention\" data-user-id=\"120791\">@RalfJ</span> please check #t-infra before reopening the tree.</p>",
        "id": 275709106,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647543223
    },
    {
        "content": "<p>Looks like <span class=\"user-mention\" data-user-id=\"120823\">@DPC</span> fixed it.</p>",
        "id": 275709189,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647543245
    },
    {
        "content": "<p>For what it's worth, I was also unable to reproduce the image build failure locally  with <code>CI=1</code> and <code>--no-cache</code>. The CI runs that alternated between succeeding and failing make me wonder if the CI builders are running in an environment with an aggressive network caching layer.</p>",
        "id": 275709228,
        "sender_full_name": "David Koloski",
        "timestamp": 1647543266
    },
    {
        "content": "<p>ye i closed it again</p>",
        "id": 275709264,
        "sender_full_name": "DPC",
        "timestamp": 1647543286
    },
    {
        "content": "<p>(and then can someone bors-retry <a href=\"https://github.com/rust-lang/rust/issues/88098\">#88098</a> since it just failed due to the tree being reopened prematurely)</p>",
        "id": 275709622,
        "sender_full_name": "Michael Goulet (compiler-errors)",
        "timestamp": 1647543457
    },
    {
        "content": "<p>done</p>",
        "id": 275709742,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647543510
    },
    {
        "content": "<p>thanks <span class=\"user-mention\" data-user-id=\"120518\">@Eric Huss</span> for working on getting this fixed!</p>",
        "id": 275709808,
        "sender_full_name": "Michael Goulet (compiler-errors)",
        "timestamp": 1647543548
    },
    {
        "content": "<p>Looks like the dist-powerpc64-linux build passed with that change, so it appears that switching to <code>cmake_build.log</code> did the trick.</p>",
        "id": 275712793,
        "sender_full_name": "David Koloski",
        "timestamp": 1647544978
    }
]