[
    {
        "content": "<p>Previous rollup has failed with: <a href=\"https://github.com/rust-lang-ci/rust/runs/1398696258\">https://github.com/rust-lang-ci/rust/runs/1398696258</a>. Not sure what's causing it. Doesn't seem to be related to any pr in the queue</p>",
        "id": 216729145,
        "sender_full_name": "DPC",
        "timestamp": 1605360684
    },
    {
        "content": "<p>looks like it was one of the prs, prob resolved</p>",
        "id": 216750446,
        "sender_full_name": "DPC",
        "timestamp": 1605388372
    },
    {
        "content": "<p>hmm, so my rollup will probably fail with the same error then</p>",
        "id": 216751960,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1605390394
    },
    {
        "content": "<p>ah, no, looks like the failures were caused by <a href=\"https://github.com/rust-lang/rust/pull/78801\">https://github.com/rust-lang/rust/pull/78801</a></p>",
        "id": 216752119,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1605390576
    }
]