[
    {
        "content": "<p>I get a warning about the latest commit not matching the try build here: <a href=\"https://github.com/rust-lang/rust/pull/80587#issuecomment-753411387\">https://github.com/rust-lang/rust/pull/80587#issuecomment-753411387</a><br>\nI thought this was to alert the user if there were multiple try builds, and the wrong one was detected, but there's only one try build in this PR. Is this a false positive, or have I made a mistake?</p>",
        "id": 221377362,
        "sender_full_name": "varkor",
        "timestamp": 1609549128
    },
    {
        "content": "<p>the same happened to ralf earlier <a href=\"https://github.com/rust-lang/rust/pull/80579#issuecomment-753370250\">https://github.com/rust-lang/rust/pull/80579#issuecomment-753370250</a></p>",
        "id": 221377517,
        "sender_full_name": "lqd",
        "timestamp": 1609549397
    },
    {
        "content": "<p>I think that's a bug in my check</p>",
        "id": 221378647,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1609551750
    },
    {
        "content": "<p>it was working when I tested it locally, but it doesn't see to work when deployed</p>",
        "id": 221378651,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1609551769
    },
    {
        "content": "<p>Opened <a href=\"https://github.com/rust-lang/crater/pull/557\">https://github.com/rust-lang/crater/pull/557</a></p>",
        "id": 221379808,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1609554023
    },
    {
        "content": "<p>I had created my fake 'try' commits incorrectly when testing</p>",
        "id": 221379811,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1609554035
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"116113\">lqd</span> <a href=\"#narrow/stream/242791-t-infra/topic/crater.20latest.20commit.20warning/near/221377517\">said</a>:</p>\n<blockquote>\n<p>the same happened to ralf earlier <a href=\"https://github.com/rust-lang/rust/pull/80579#issuecomment-753370250\">https://github.com/rust-lang/rust/pull/80579#issuecomment-753370250</a></p>\n</blockquote>\n<p>oh, it did... I had not even noticed that warning^^</p>",
        "id": 221400546,
        "sender_full_name": "RalfJ",
        "timestamp": 1609595006
    },
    {
        "content": "<p>Once it's fixed, we might want to make it more prominent</p>",
        "id": 221403358,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1609599862
    },
    {
        "content": "<p>once of my previous macro-hygiene-fix PRs with merged with an unexpectedly large number of regressions, due to an old try build being used on Crter</p>",
        "id": 221403373,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1609599902
    },
    {
        "content": "<p>which is what prompted me to add the check</p>",
        "id": 221403394,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1609599938
    },
    {
        "content": "<p>makes sense. (in this case I almost dliberately used an old try build since the changes were only in tests and docs, but then I was like \"whatever, try builds are quick\"^^)</p>",
        "id": 221408238,
        "sender_full_name": "RalfJ",
        "timestamp": 1609607961
    }
]