[
    {
        "content": "<p>Strange error here: <a href=\"https://github.com/rust-lang/rust/pull/75687#issuecomment-680872483\">https://github.com/rust-lang/rust/pull/75687#issuecomment-680872483</a></p>",
        "id": 208089426,
        "sender_full_name": "Amanieu",
        "timestamp": 1598448003
    },
    {
        "content": "<p>From the raw log:</p>\n<div class=\"codehilite\"><pre><span></span><code>2020-08-26T13:11:35.4854650Z Traceback (most recent call last):\n2020-08-26T13:11:35.4854844Z Creating issue:\n2020-08-26T13:11:35.4855059Z   File &quot;/home/runner/work/rust/rust/src/tools/publish_toolstate.py&quot;, line 349, in &lt;module&gt;\n2020-08-26T13:11:35.4855191Z     main()\n2020-08-26T13:11:35.4855317Z   File &quot;/home/runner/work/rust/rust/src/tools/publish_toolstate.py&quot;, line 319, in main\n2020-08-26T13:11:35.4856693Z {&quot;body&quot;: &quot;Hello, this is your friendly neighborhood mergebot.\\nAfter merging PR rust-lang/rust#75687, I observed that the tool miri has failing tests.\\nA follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.\\n\\ncc @TimDiekmann, do you think you would have time to do the follow-up work?\\nIf so, that would be great!\\n\\nAnd nominating for compiler team prioritization.\\n\\n&quot;, &quot;assignees&quot;: [&quot;oli-obk&quot;, &quot;eddyb&quot;, &quot;RalfJung&quot;], &quot;labels&quot;: [&quot;A-miri&quot;, &quot;C-bug&quot;], &quot;title&quot;: &quot;`miri` no longer builds after rust-lang/rust#75687&quot;}\n2020-08-26T13:11:35.4862491Z Unexpected error when creating issue for status regression: &lt;type &#39;exceptions.NameError&#39;&gt;\n2020-08-26T13:11:35.4865706Z     cur_datetime\n2020-08-26T13:11:35.4865922Z   File &quot;/home/runner/work/rust/rust/src/tools/publish_toolstate.py&quot;, line 250, in update_latest\n2020-08-26T13:11:35.4868312Z     relevant_pr_number, relevant_pr_user, LABELS.get(tool, &#39;&#39;),\n2020-08-26T13:11:35.4869528Z   File &quot;/home/runner/work/rust/rust/src/tools/publish_toolstate.py&quot;, line 176, in issue\n2020-08-26T13:11:35.4871883Z     &#39;Authorization&#39;: &#39;token &#39; + github_token,\n2020-08-26T13:11:35.4872228Z NameError: global name &#39;github_token&#39; is not defined\n</code></pre></div>",
        "id": 208089465,
        "sender_full_name": "Amanieu",
        "timestamp": 1598448038
    },
    {
        "content": "<p>ah token issue. it tried to create an issue that miri is broken but failed at the token <span aria-label=\"grinning\" class=\"emoji emoji-1f600\" role=\"img\" title=\"grinning\">:grinning:</span></p>",
        "id": 208092818,
        "sender_full_name": "DPC",
        "timestamp": 1598449673
    },
    {
        "content": "<p><code>$TOOLSTATE_REPO_ACCESS_TOKEN</code> is defined. but the problem is <code>$TOOLSTATE_VALIDATE_MAINTAINERS_REPO</code> is undefined</p>",
        "id": 208093086,
        "sender_full_name": "kennytm",
        "timestamp": 1598449785
    },
    {
        "content": "<p>Hello infra folks!  Posting because I got this in <a href=\"https://github.com/rust-lang/rust/pull/75912#issuecomment-681110514\">https://github.com/rust-lang/rust/pull/75912#issuecomment-681110514</a> after it was successfully bors-merged:<br>\n<a href=\"/user_uploads/4715/yPCGcoLWYzLkfgUBYPMGmIck/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/4715/yPCGcoLWYzLkfgUBYPMGmIck/image.png\" title=\"image.png\"><img src=\"/user_uploads/4715/yPCGcoLWYzLkfgUBYPMGmIck/image.png\"></a></div>",
        "id": 208147623,
        "sender_full_name": "scottmcm",
        "timestamp": 1598475476
    },
    {
        "content": "<p>Oh, looking at the log this might be the problem:</p>\n<div class=\"codehilite\"><pre><span></span><code>NameError: global name &#39;github_token&#39; is not defined\n</code></pre></div>",
        "id": 208149062,
        "sender_full_name": "scottmcm",
        "timestamp": 1598476120
    },
    {
        "content": "<p>merged with the other report</p>",
        "id": 208149165,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1598476192
    },
    {
        "content": "<p>and gah this also happened today</p>",
        "id": 208149172,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1598476199
    },
    {
        "content": "<p>too tired, can someone look into it? otherwise it'll wait till morning</p>",
        "id": 208149231,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1598476214
    },
    {
        "content": "<p>seems non-urgent</p>",
        "id": 208149302,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476263
    },
    {
        "content": "<p>I'll take a quick peek</p>",
        "id": 208149314,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476270
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"125254\">@kennytm</span> you seem to have diagnosed this but I'm not following your diagnosis</p>",
        "id": 208149963,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476551
    },
    {
        "content": "<p><a href=\"https://github.com/rust-lang/rust/blob/ffd59bf9c62125813abae8ca52f0ac3a67459e8f/src/tools/publish_toolstate.py#L279-L281\">https://github.com/rust-lang/rust/blob/ffd59bf9c62125813abae8ca52f0ac3a67459e8f/src/tools/publish_toolstate.py#L279-L281</a></p>",
        "id": 208150062,
        "sender_full_name": "kennytm",
        "timestamp": 1598476605
    },
    {
        "content": "<p><del>the <code>github_token = os.environ.get('TOOLSTATE_REPO_ACCESS_TOKEN')</code> line should be moved above <code>if repo:</code> i think</del></p>",
        "id": 208150105,
        "sender_full_name": "kennytm",
        "timestamp": 1598476633
    },
    {
        "content": "<p>hm but why did this just start failing...?</p>",
        "id": 208150118,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476642
    },
    {
        "content": "<p>and inconsistently, too</p>",
        "id": 208150149,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476661
    },
    {
        "content": "<p>hm okay I have a theory</p>",
        "id": 208150263,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476723
    },
    {
        "content": "<p><a href=\"https://github.com/rust-lang/rust/commit/2e6f2e885506ee46ea32622e33fe74d99774cf57\">https://github.com/rust-lang/rust/commit/2e6f2e885506ee46ea32622e33fe74d99774cf57</a></p>",
        "id": 208150265,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476724
    },
    {
        "content": "<p>that commit changed the scoping rules for github_token</p>",
        "id": 208150280,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476731
    },
    {
        "content": "<p>yes</p>",
        "id": 208150306,
        "sender_full_name": "kennytm",
        "timestamp": 1598476745
    },
    {
        "content": "<p>previously it was defined in global scope, so when we went to execute the issue function things worked</p>",
        "id": 208150322,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476753
    },
    {
        "content": "<p>this is why we have compilers...</p>",
        "id": 208150367,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476773
    },
    {
        "content": "<p>I think I can just prefix github_token = by \"global \"</p>",
        "id": 208150502,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476826
    },
    {
        "content": "<p>but now I'm worried all our variables are implicitly global in def main</p>",
        "id": 208150550,
        "sender_full_name": "simulacrum",
        "timestamp": 1598476850
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"125254\">@kennytm</span> up for reviewing <a href=\"https://github.com/rust-lang/rust/pull/75958\">https://github.com/rust-lang/rust/pull/75958</a>?</p>",
        "id": 208151032,
        "sender_full_name": "simulacrum",
        "timestamp": 1598477125
    },
    {
        "content": "<p>Apologies, I did not catch that it was global. <span aria-label=\"frown\" class=\"emoji emoji-1f641\" role=\"img\" title=\"frown\">:frown:</span></p>",
        "id": 208155945,
        "sender_full_name": "Eric Huss",
        "timestamp": 1598480066
    },
    {
        "content": "<p>no worries, I didn't either</p>",
        "id": 208162661,
        "sender_full_name": "simulacrum",
        "timestamp": 1598484809
    },
    {
        "content": "<p>I always forget that's a thing in python</p>",
        "id": 208162668,
        "sender_full_name": "simulacrum",
        "timestamp": 1598484814
    },
    {
        "content": "<p>(This caused some confusion as the bot posted some nonsensical things about Miri failures. In case something Miri-specific like this happens again, a ping would be appreciated so I do not have to debug things that have already been figured out^^.)</p>",
        "id": 208184523,
        "sender_full_name": "RalfJ",
        "timestamp": 1598512542
    }
]